version: '3.2'

services:
  node:
    build:
      dockerfile: ./docker/front.dockerfile
      context: .
    image: node
    container_name: node
    ports:
      - 3000:3000
    networks:
      - production-network

  contatos:
    build:
      dockerfile: ./docker/contatos.dockerfile
      context: .
    image: python3
    container_name: python3
    ports:
      - 8000:8000
    networks:
      - production-network
    depends_on:
      - db
    command: >
      sh -c "
             python3 manage.py migrate
             python3 manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - production-network


networks:
  production-network:
    driver: bridge
