# Generated by Django 3.2.6 on 2021-08-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
